apiVersion: batch/v1
kind: Job
metadata:
  name: {{ randAlphaNum 10 | lower | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - |
           for i in 9 8 7 6 5 4 3 2 1 ; do
             echo $i
           done
           exit 1 # Intentional failure
      restartPolicy: Never

