---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": {{ .Values.global.helm.resourcePolicy }}
  name: {{ .Values.global.name }}
spec:
  accessModes:
  - {{ .Values.global.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.global.storage.size }}
  storageClassName: {{ .Values.global.storage.class }}
  volumeMode: Filesystem
status:
  accessModes:
  - {{ .Values.global.storage.accessMode }}
  capacity:
    storage: {{ .Values.global.storage.size }}
