{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" . }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  {{- range $key,$value:= .Values.configs }}
  {{$key}}: {{ $value | quote }}
  {{- end }}
{{- end }}
