---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.name" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.infisicalAutoReload | or .Values.infisical.enabled }}
  annotations:
      secrets.infisical.com/auto-reload: "true"
  {{- end }}
spec:
  minReadySeconds: {{ .Values.minReadySeconds }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "common.labels.matchLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.configs }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secrets }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.sealedSecrets.enabled }}
        checksum/sealedSecret: {{ include (print $.Template.BasePath "/sealed-secrets.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: {{ .Values.metrics.path | required "metrics.path is required" }}
        prometheus.io/port: {{ .Values.port | quote }}
        {{- end }}
        {{- range $key,$value:= .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if  .Values.extraVolumes | or .Values.volume }}
      volumes:

      {{- if  .Values.volume }}
        - name: {{ include "common.names.volume" . }}
          configMap:
            name: {{ .Values.volume.configMap | default  .Release.Name  }}
      {{- end }}

      {{- range $extraVolumes:=.Values.extraVolumes }}
        - {{- toYaml $extraVolumes | nindent 10 }}
      {{- end }}

      {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: {{ include "common.images.image" . }}
          args: {{ .Values.args | toJson }}
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}

            {{- if .Values.otel.enabled | and .Values.otel.env }}
            {{- toYaml .Values.otel.env | nindent 12 }}
            {{- end }}

            {{- if .Values.addGateWayPublicKey }}
            - name: GATEWAY__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.gatewayCertSecret" . }}
                  key: tls.crt
            {{- end }}

            {{- if .Values.addGateWayPrivateKey }}
            - name: PRIVATE_KEY__KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.gatewayCertSecret" . }}
                  key: tls.key
            {{- end }}


            {{- if .Values.addRabbitMQDefaultUrl }}
            - name: RABBITMQ__URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.rabbitmqCredentials" . }}
                  key: url
            {{- end }}

            {{- if  .Values.addRabbitMQDefaultCred }}
            - name: RABBITMQ__USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.rabbitmqCredentials" . }}
                  key: username

            - name: RABBITMQ__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.rabbitmqCredentials" . }}
                  key: password
            {{- end }}

          envFrom:
          {{- if .Values.envFrom }}
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.configs }}
            - configMapRef:
                name: {{ include "common.names.name" . }}
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "common.names.name" . }}
          {{- end }}

          {{- if .Values.sealedSecrets.enabled }}
            - secretRef:
                name: {{ .Values.sealedSecrets.name | default ( include "common.names.sealedSecret" . ) }}
          {{- end }}

          {{- if .Values.infisical.enabled }}
            - secretRef:
                name: {{ include "common.names.infisical.managedSecret" . }}
          {{- end }}

          resources: {{- toYaml ( .Values.resources | required "provide resources" ) | nindent 12 }}

          ports:
            - containerPort: {{ .Values.port }}
              name: http

          {{- if  .Values.readinessProbe.enabled }}
          readinessProbe: {{- toYaml .Values.readinessProbe.spec | nindent 12 }}
          {{- end }}

          {{- if  .Values.livenessProbe.enabled }}
          livenessProbe: {{- toYaml .Values.livenessProbe.spec | nindent 12 }}
          {{- end }}

          {{- if  .Values.extraVolumeMounts | or .Values.volume }}
          volumeMounts:

          {{- if .Values.volume }}
            - name: {{ include "common.names.volume" . }}
              mountPath: {{ .Values.volume.mountPath }}
              readOnly: true
              subPath: {{ .Values.volume.key }}
          {{- end }}

          {{- range $extraVolumeMounts:=.Values.extraVolumeMounts }}
            - {{- toYaml $extraVolumeMounts | nindent 14 }}
          {{- end }}

          {{- end }}
