{{ if .Values.infisical.enabled }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "common.names.infisical.secret" . }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: {{ .Values.infisical.sealedSecret.name | default ( include "common.names.infisical.token" . ) }}
        secretNamespace: {{  .Values.infisical.sealedSecret.namespace | default .Release.Namespace }}
      secretsScope:
        secretsPath: {{ .Values.infisical.secretsScope.secretsPath | required "infisical.secretsScope.secretsPath value is required" }}
        envSlug: {{ .Values.infisical.secretsScope.envSlug | required "infisical.secretsScope.envSlug value is required" }}
  managedSecretReference:
    secretName: {{ include "common.names.infisical.managedSecret" . }}
    secretNamespace: {{  .Values.infisical.managedSecret.namespace | default .Release.Namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.infisical.sealedSecret.name | default ( include "common.names.infisical.token" . ) }}
  namespace: {{  .Values.infisical.sealedSecret.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  encryptedData:
    infisicalToken: {{ .Values.infisical.sealedSecret.token | required "infisical.tokenSecret.encryptedData value is required" }}
{{ end }}
