{{- if .Values.networkPolicy.enabled | and  .Values.otel.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.name" . }}-otel
spec:
  podSelector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}

  policyTypes:
    - Egress

  egress:
    - ports:
        - port: 4317
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: groundcover
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: groundcover
              app.kubernetes.io/name: opentelemetry-collector
{{- end }}
---

{{- if .Values.networkPolicy.enabled | and  .Values.metrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.name" . }}-metrics
spec:
  podSelector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: groundcover
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: groundcover
              app.kubernetes.io/name: custom-metrics
      ports:
        - port: {{ .Values.port }}
          protocol: TCP
{{- end }}
