{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.name" . }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  {{- range $key,$value:= .Values.secrets }}
  {{- if $value }}
  {{$key}}: {{ $value | b64enc }}
  {{- else }}
  {{$key}}: ""
  {{- end }}
  {{- end }}
{{- end }}
