apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
