---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neuvector-init
  namespace: neuvector
data:
  passwordprofileinitcfg.yaml: |
    always_reload: true
    active_profile_name: default
    pwd_profiles:
    - name: default
      comment: AKDB-Default
      min_len: 12
      min_uppercase_count: 1
      min_lowercase_count: 1
      min_digit_count: 1
      min_special_count: 1
      enable_block_after_failed_login: true
      block_after_failed_login_count: 5
      block_minutes: 1
      enable_password_expiration: false
      password_expire_after_days: 0
      enable_password_history: false
      password_keep_history_count: 0
      session_timeout: 3600
  roleinitcfg.yaml: |
    always_reload: true
    roles:
    - Comment: Admin role for downstream clusters
      Name: AKDBAdmin
      Permissions:
        - id: vulnerability
          read: true
          write: true
        - id: config
          read: true
          write: true
        - id: rt_scan
          read: true
          write: true
        - id: reg_scan
          read: true
          write: true
        - id: ci_scan
          write: true
        - id: rt_policy
          read: true
          write: true
        - id: admctrl
          read: true
          write: true
        - id: compliance
          read: true
          write: true
        - id: audit_events
          read: true
        - id: security_events
          read: true
        - id: events
          read: true
    - Comment: CI/CD roles for automation
      Name: ciopsAKDB
      Permissions:
        - id: vulnerability
          read: true
          write: true
        - id: rt_scan
          read: true
          write: true
        - id: reg_scan
          read: true
          write: true
        - id: ci_scan
          write: true
  sysinitcfg.yaml: |
    always_reload: {{ .Values.neuvector.sysinitcfg.alwaysReload }}
    New_Service_Policy_Mode: {{ .Values.neuvector.sysinitcfg.newServicePolicyMode }}
    New_Service_Profile_Baseline: {{ .Values.neuvector.sysinitcfg.newServiceProfileBaseline }}
    Auth_By_Platform: false
    Cluster_Name: {{ .Values.neuvector.sysinitcfg.clusterName }}
    Monitor_Service_Mesh: {{ .Values.neuvector.sysinitcfg.monitorServiceMesh }}
    Registry_Http_Proxy_Status: {{ .Values.neuvector.sysinitcfg.registryHttpProxy }}
    Registry_Https_Proxy_Status: {{ .Values.neuvector.sysinitcfg.registryHttpsProxy }}
    Registry_Http_Proxy:
      URL: {{ .Values.neuvector.sysinitcfg.proxyURL }}
    Registry_Https_Proxy:
      URL: {{ .Values.neuvector.sysinitcfg.proxyURL }}
    Xff_Enabled: {{ .Values.neuvector.sysinitcfg.xffEnabled }}
    Net_Service_Status: {{ .Values.neuvector.sysinitcfg.netServiceStatus }}
    Net_Service_Policy_Mode: {{ .Values.neuvector.sysinitcfg.netServicePolicyMode }}
    Scanner_Autoscale:
      Strategy: {{ .Values.neuvector.sysinitcfg.scannerAutoscale.strategy }}
      Min_Pods: {{ .Values.neuvector.sysinitcfg.scannerAutoscale.minPods }}
      Max_Pods: {{ .Values.neuvector.sysinitcfg.scannerAutoscale.maxPods }}
    No_Telemetry_Report: {{ .Values.neuvector.sysinitcfg.noTelemetryReport }}
    Scan_Config:
      Auto_Scan: {{ .Values.neuvector.sysinitcfg.autoScan }}
    Unused_Group_Aging: {{ .Values.neuvector.sysinitcfg.unusedGroupAging }}
