apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: kasten-io
  annotations:
    meta.helm.sh/release-name: kasten
    meta.helm.sh/release-namespace: kasten-io
  labels:
    app: k10
    app.kubernetes.io/instance: kasten
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k10
    service: gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 31580
  selector:
    service: gateway
  externalTrafficPolicy: Cluster
