apiVersion: v1
kind: Service
metadata:
  name: gateway-admin
  namespace: kasten-io
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    service: gateway
